Console Error
Certificate generation API call failed: "102.218.215.3: Invalid response from http://robinwebservices.com/.well-known/acme-challenge/mtieaajQX8zCaCNbTmeAs5-J1ZKgZOHeK8mFYJ9D8bc: 404"

src/services/cert-magic.ts (123:13) @ generateCertificate

  121 |         // Ignore JSON parsing error if response body is not JSON
  122 |     }
> 123 |     console.error("Certificate generation API call failed:", errorMessage);
      |             ^
  124 |     throw new Error(errorMessage); // Throw the specific error from backend
  125 |   }
  126 |

Console Error

Error: 102.218.215.3: Invalid response from http://robinwebservices.com/.well-known/acme-challenge/mtieaajQX8zCaCNbTmeAs5-J1ZKgZOHeK8mFYJ9D8bc: 404

src/services/cert-magic.ts (124:11) @ generateCertificate

  122 |     }
  123 |     console.error("Certificate generation API call failed:", errorMessage);
> 124 |     throw new Error(errorMessage); // Throw the specific error from backend
      |           ^
  125 |   }
  126 |
  127 |   // Assuming the backend returns data conforming to the Certificate interface

It seem the domain validation is trying to run in the local host. Unfortunately, user will not be hosting on our server, so the validation challenge will have be provided to the user in the frontend interface to manually put it in it hosting, then we can validate it if present, incase it is not, we can let user retry until it validated.